api_version: 2
vm:
  base_box: 'ubuntu/bionic64'
  base_box_version: '20201007.0.0'
  name: 'ubuntu-dev-box'
  cpus: 1
  memory: 1024
  providers:
    virtualbox:
      gui: true
provisioners:
  - base:
      enable: true
      before: :all
      type: shell
      path: provision/base.sh
      privileged: true
  - python:
      enable: true
      type: shell
      path: provision/python.sh
      privileged: true
  - docker:
      enable: true
      type: shell
      path: provision/docker.sh
      privileged: true
  - web-development:
      enable: true
      type: shell
      path: provision/web-development.sh
      privileged: true
  - desktop:
      enable: true
      type: shell
      path: provision/desktop.sh
      privileged: true
  - clean-up:
      enable: true
      after: :all
      type: shell
      path: provision/clean-up.sh
      privileged: true
